version: '3.9'
services:
  postgres:
    image: postgres:16-alpine
    container_name: finalbodweb-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: finalbodweb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - finalbodweb_pg_data:/var/lib/postgresql/data

volumes:
  finalbodweb_pg_data:
